/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza.view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pizza.model.produto;
import pizza.model.produto_fornecer;

/**
 *
 * @author Luiza
 */
public class comprar extends javax.swing.JFrame {

    /**
     * Creates new form comprar
     */
    public comprar() {
        initComponents();
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        voltar = new javax.swing.JButton();
        pizza = new javax.swing.JComboBox<>();
        refri = new javax.swing.JComboBox<>();
        quantp = new javax.swing.JComboBox<>();
        quantr = new javax.swing.JComboBox<>();
        finalizar = new javax.swing.JButton();
        verpedido = new javax.swing.JButton();
        pedir = new javax.swing.JButton();
        usuario1 = new javax.swing.JLabel();
        usuario2 = new javax.swing.JLabel();
        srefri = new javax.swing.JCheckBox();
        sazeitona = new javax.swing.JCheckBox();
        ketchup = new javax.swing.JCheckBox();
        pizzad = new javax.swing.JCheckBox();
        usuario3 = new javax.swing.JLabel();
        local = new javax.swing.JTextField();
        entregar = new javax.swing.JRadioButton();
        buscar = new javax.swing.JRadioButton();
        pedido = new javax.swing.JFormattedTextField();
        usuario4 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        usuario5 = new javax.swing.JLabel();
        total = new javax.swing.JFormattedTextField();
        vertotal = new javax.swing.JButton();
        atualizar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        cardapio = new javax.swing.JToggleButton();
        contato = new javax.swing.JButton();
        telacad = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        voltar.setBackground(new java.awt.Color(255, 106, 0));
        voltar.setText("<");
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });
        getContentPane().add(voltar);
        voltar.setBounds(0, 0, 40, 23);

        pizza.setBackground(new java.awt.Color(255, 113, 0));
        pizza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Calabresa", "Mussalera", "Portuguesa", "Frango com Catupiry", "Especial - Pizzarela" }));
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });
        getContentPane().add(pizza);
        pizza.setBounds(100, 160, 130, 30);

        refri.setBackground(new java.awt.Color(255, 111, 0));
        refri.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Coca - Cola ", "Pepsi", "Fanta(Uva)", "Fanta(Laranja)", "Fanta(Guarana)", "Guarana-Jesus", "Kuat", "Sukita", " " }));
        refri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refriActionPerformed(evt);
            }
        });
        getContentPane().add(refri);
        refri.setBounds(100, 200, 130, 30);

        quantp.setBackground(new java.awt.Color(255, 116, 0));
        quantp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        quantp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantpActionPerformed(evt);
            }
        });
        getContentPane().add(quantp);
        quantp.setBounds(250, 160, 80, 30);

        quantr.setBackground(new java.awt.Color(255, 125, 0));
        quantr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        quantr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantrActionPerformed(evt);
            }
        });
        getContentPane().add(quantr);
        quantr.setBounds(250, 200, 80, 30);

        finalizar.setBackground(new java.awt.Color(207, 84, 25));
        finalizar.setForeground(new java.awt.Color(1, 1, 1));
        finalizar.setText("FINALIZAR");
        finalizar.setEnabled(false);
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(finalizar);
        finalizar.setBounds(350, 450, 110, 23);

        verpedido.setBackground(new java.awt.Color(207, 84, 25));
        verpedido.setForeground(new java.awt.Color(1, 1, 1));
        verpedido.setText("VER PEDIDO");
        verpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verpedidoActionPerformed(evt);
            }
        });
        getContentPane().add(verpedido);
        verpedido.setBounds(20, 450, 130, 23);

        pedir.setBackground(new java.awt.Color(207, 84, 25));
        pedir.setForeground(new java.awt.Color(1, 1, 1));
        pedir.setText("PEDIR");
        pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirActionPerformed(evt);
            }
        });
        getContentPane().add(pedir);
        pedir.setBounds(160, 450, 80, 23);

        usuario1.setFont(new java.awt.Font("URW Palladio L", 1, 18)); // NOI18N
        usuario1.setForeground(new java.awt.Color(1, 1, 1));
        usuario1.setText("PIZZA");
        getContentPane().add(usuario1);
        usuario1.setBounds(30, 160, 70, 30);

        usuario2.setFont(new java.awt.Font("URW Palladio L", 1, 18)); // NOI18N
        usuario2.setForeground(new java.awt.Color(1, 1, 1));
        usuario2.setText("PEDIDO");
        getContentPane().add(usuario2);
        usuario2.setBounds(250, 330, 90, 30);

        srefri.setText("Sem Refri");
        srefri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srefriActionPerformed(evt);
            }
        });
        getContentPane().add(srefri);
        srefri.setBounds(340, 200, 80, 30);

        sazeitona.setText("Sem Azeitona");
        getContentPane().add(sazeitona);
        sazeitona.setBounds(30, 250, 100, 23);

        ketchup.setText("Com Ketchup e Maionese");
        getContentPane().add(ketchup);
        ketchup.setBounds(150, 250, 170, 23);

        pizzad.setText("Pizza Doce");
        pizzad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzadActionPerformed(evt);
            }
        });
        getContentPane().add(pizzad);
        pizzad.setBounds(340, 160, 100, 30);

        usuario3.setFont(new java.awt.Font("URW Palladio L", 1, 18)); // NOI18N
        usuario3.setForeground(new java.awt.Color(1, 1, 1));
        usuario3.setText("REFRI");
        getContentPane().add(usuario3);
        usuario3.setBounds(30, 200, 70, 30);
        getContentPane().add(local);
        local.setBounds(110, 290, 130, 30);

        entregar.setText("Entregar");
        entregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregarActionPerformed(evt);
            }
        });
        getContentPane().add(entregar);
        entregar.setBounds(360, 290, 80, 30);

        buscar.setText("Ir Buscar");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar);
        buscar.setBounds(260, 290, 80, 30);
        getContentPane().add(pedido);
        pedido.setBounds(340, 330, 60, 30);

        usuario4.setFont(new java.awt.Font("URW Palladio L", 1, 18)); // NOI18N
        usuario4.setForeground(new java.awt.Color(1, 1, 1));
        usuario4.setText("LOCAL");
        getContentPane().add(usuario4);
        usuario4.setBounds(10, 290, 70, 30);

        cancelar.setBackground(new java.awt.Color(207, 84, 25));
        cancelar.setForeground(new java.awt.Color(1, 1, 1));
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(350, 410, 110, 23);

        usuario5.setFont(new java.awt.Font("URW Palladio L", 1, 18)); // NOI18N
        usuario5.setForeground(new java.awt.Color(1, 1, 1));
        usuario5.setText("TOTAL(R$)");
        getContentPane().add(usuario5);
        usuario5.setBounds(10, 330, 140, 30);

        total.setEnabled(false);
        getContentPane().add(total);
        total.setBounds(110, 330, 130, 30);

        vertotal.setBackground(new java.awt.Color(255, 102, 0));
        vertotal.setText("VER TOTAL");
        vertotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vertotalActionPerformed(evt);
            }
        });
        getContentPane().add(vertotal);
        vertotal.setBounds(170, 410, 120, 20);

        atualizar.setBackground(new java.awt.Color(255, 102, 0));
        atualizar.setText("ATUALIZAR PEDIDO");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(20, 410, 140, 20);

        alterar.setBackground(new java.awt.Color(207, 84, 25));
        alterar.setForeground(new java.awt.Color(1, 1, 1));
        alterar.setText("ALT");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(380, 10, 80, 23);

        cardapio.setBackground(new java.awt.Color(207, 84, 25));
        cardapio.setText("CARDAPIO");
        cardapio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardapioActionPerformed(evt);
            }
        });
        getContentPane().add(cardapio);
        cardapio.setBounds(260, 10, 100, 23);

        contato.setBackground(new java.awt.Color(207, 84, 25));
        contato.setText("CONTATO");
        contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contatoActionPerformed(evt);
            }
        });
        getContentPane().add(contato);
        contato.setBounds(160, 10, 90, 23);

        telacad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastro.png"))); // NOI18N
        getContentPane().add(telacad);
        telacad.setBounds(0, 0, 470, 490);

        setBounds(0, 0, 487, 529);
    }// </editor-fold>//GEN-END:initComponents

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
       cadastro c = new cadastro();
       c.setVisible(true);
       dispose();
    }//GEN-LAST:event_voltarActionPerformed

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzaActionPerformed

    private void refriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refriActionPerformed

    private void pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirActionPerformed
 produto pf = new produto();
        if(local.getText().equals("") && entregar.isSelected()||pedido.getText().equals("")||quantp.getSelectedItem().equals("0")||pizza.getSelectedItem().equals("Selecione")
        ||refri.getSelectedItem().equals("Selecione")&& !srefri.isSelected()){
           JOptionPane.showMessageDialog(null,"Preencha as lacunas");
       }
        else if(!buscar.isSelected()&&!entregar.isSelected()){
            JOptionPane.showMessageDialog(null,"Marque algo");
        }
        else{
    
      pf.setPedido((Integer.parseInt(pedido.getText())));
      pf.setLocal(local.getText());
      pf.setPizza((String)pizza.getSelectedItem());
       pf.setRefri((String)refri.getSelectedItem());
       pf.setQuantp((Integer.parseInt((String)quantp.getSelectedItem())));
        pf.setQuantr(Integer.parseInt((String)quantr.getSelectedItem()));
        pf.setSrefri((Boolean)srefri.isSelected());
        pf.setSazeitona((Boolean)sazeitona.isSelected());
        pf.setKetchup((Boolean)ketchup.isSelected());
        pf.setBuscar((Boolean)buscar.isSelected());
        pf.setEntregar((Boolean)entregar.isSelected());
        
      
      
        JOptionPane.showMessageDialog(null, pf.SalvarCC());
       
    
     finalizar.setEnabled(true);
     
            
     
     

     
        }
        
    }//GEN-LAST:event_pedirActionPerformed

    private void quantrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantrActionPerformed

    private void quantpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantpActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
     produto p = new produto();
        
     JOptionPane.showMessageDialog(null,"OBRIGADO POR PEDIR NA PIZZARELA,VOLTE SEMPRE!");
     JOptionPane.showMessageDialog(null,"QUALQUER IMPREVISTO NOS CONTATE:"+"\n 98558-5542");
     int nota = Integer.parseInt(JOptionPane.showInputDialog("Informe-nos sua nota para o nosso aplicativo (1 Á 10)"));
      JOptionPane.showMessageDialog(null,"SUA NOTA FOI: "+nota+"\n OBRIGADO POR PEDIR NA PIZZARELA!");
      
      p.setPedido((Integer.parseInt(pedido.getText())));
      p.DeleteALL();
      System.exit(0);
      
    }//GEN-LAST:event_finalizarActionPerformed

    private void srefriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srefriActionPerformed
       if(srefri.isSelected()){
         refri.setEnabled(false);
         quantr.setEnabled(false);
         quantr.setSelectedItem(0);
         refri.setSelectedItem(0);
    }
      
       
       else{
           refri.setEnabled(true);
           quantr.setEnabled(true);
    }//GEN-LAST:event_srefriActionPerformed
    }
    private void pizzadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzadActionPerformed
          if(pizzad.isSelected()){
        pizza.removeAllItems();
        pizza.addItem("Selecione");
        pizza.addItem("Chocolate");
        pizza.addItem("Beijinho");
        pizza.addItem("Chocolate Branco");
        pizza.addItem("Brigadeiro");
    }
      
       
       else{
         pizza.removeAllItems();
        pizza.addItem("Calabresa");
        pizza.addItem("Mussalera");
        pizza.addItem("Portuguesa");
        pizza.addItem("Brigadeiro");
        pizza.addItem("Frango com Catupiry");
        pizza.addItem("Especial-Pizzarela");
          }
          
    }//GEN-LAST:event_pizzadActionPerformed

    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        if(buscar.isSelected()){
           entregar.setEnabled(false);
           local.setEnabled(false);
        }
        else{
         entregar.setEnabled(true);
           local.setEnabled(true);
        }
    }//GEN-LAST:event_buscarActionPerformed

    private void entregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregarActionPerformed
       if(entregar.isSelected()){
           buscar.setEnabled(false);
       }
       else{
        buscar.setEnabled(true);
       }
    }//GEN-LAST:event_entregarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
       try{
        int cod = Integer.parseInt(JOptionPane.showInputDialog("Digite o código ")); 
     produto c = new produto();
        c.setPedido(cod);
        JOptionPane.showMessageDialog(null, c.DeletarCC());
      local.setEnabled(true);
      quantr.setEnabled(true);
      quantp.setEnabled(true);
       refri.setEnabled(true);
     pizza.setEnabled(true);
     sazeitona.setEnabled(true); 
     srefri.setEnabled(true);
     pizzad.setEnabled(true); 
     buscar.setEnabled(true);
     pedir.setEnabled(true);
     entregar.setEnabled(true);
     ketchup.setEnabled(true);
     pedido.setEnabled(true);
     local.setText("");
     total.setText("");
     pedido.setText("");
     pizzad.setSelected(false);
     srefri.setSelected(false);
     ketchup.setSelected(false);
     sazeitona.setSelected(false);
        
   }
    catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro: " +erro.getMessage());
                Logger.getLogger(comprar.class.getName()).log(Level.SEVERE, null, erro);
   
    }        // TODO add your handling code here:

    }//GEN-LAST:event_cancelarActionPerformed

    private void verpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verpedidoActionPerformed
        if(evt.getSource()== verpedido){
            
            produto pf = new produto();
            try {
                String ccode = JOptionPane.showInputDialog("Digite o código: ");
                BufferedReader bf = new BufferedReader(new FileReader(ccode+"cc.txt"));
                // criando o arquivo de leitura de caracteres
                
                pedido.setText(bf.readLine());
                local.setText(bf.readLine());
                 pizza.setSelectedItem(bf.readLine());
                 refri.setSelectedItem(bf.readLine());
                quantp.setSelectedItem(bf.readLine());
                quantr.setSelectedItem(bf.readLine());
               pizzad.setSelected(Boolean.parseBoolean(bf.readLine()));
               srefri.setSelected(Boolean.parseBoolean(bf.readLine()));
               sazeitona.setSelected(Boolean.parseBoolean(bf.readLine()));
               ketchup.setSelected(Boolean.parseBoolean(bf.readLine()));
                buscar.setSelected(Boolean.parseBoolean(bf.readLine()));
                entregar.setSelected(Boolean.parseBoolean(bf.readLine()));
                 total.setText(bf.readLine());
                bf.close();
                
       pf.setPizza((String)pizza.getSelectedItem());
       pf.setRefri((String)refri.getSelectedItem());
       pf.setQuantp((Integer.parseInt((String)quantp.getSelectedItem())));
        pf.setQuantr(Integer.parseInt((String)quantr.getSelectedItem()));
     pf.CalcValor();
     total.setText(""+pf.getTotal());
           local.setEnabled(false);
      quantr.setEnabled(false);
      quantp.setEnabled(false);
       refri.setEnabled(false);
     pizza.setEnabled(false);
     sazeitona.setEnabled(false); 
     srefri.setEnabled(false);
     pizzad.setEnabled(false); 
     buscar.setEnabled(false);
     pedir.setEnabled(false);
     entregar.setEnabled(false);
     ketchup.setEnabled(false);
     pedido.setEnabled(false);
                
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro: " +erro.getMessage());
                Logger.getLogger(comprar.class.getName()).log(Level.SEVERE, null, erro);
         local.setEnabled(true);
      quantr.setEnabled(true);
      quantp.setEnabled(true);
       refri.setEnabled(true);
     pizza.setEnabled(true);
     sazeitona.setEnabled(true); 
     srefri.setEnabled(true);
     pizzad.setEnabled(true); 
     buscar.setEnabled(true);
     pedir.setEnabled(true);
     entregar.setEnabled(true);
     ketchup.setEnabled(true);
     pedido.setEnabled(true);
            }
        }
        
    }//GEN-LAST:event_verpedidoActionPerformed

    private void vertotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vertotalActionPerformed
       
        if(quantr.getSelectedItem().equals(0)|| quantp.getSelectedItem().equals(0)){
            JOptionPane.showMessageDialog(null,"INFORME OS VALORES");
        }
        else{
       produto pf = new produto();
       pf.setPizza((String)pizza.getSelectedItem());
       pf.setRefri((String)refri.getSelectedItem());
       pf.setQuantp((Integer.parseInt((String)quantp.getSelectedItem())));
        pf.setQuantr(Integer.parseInt((String)quantr.getSelectedItem()));
     pf.CalcValor();
     total.setText(""+pf.getTotal());
        }
    }//GEN-LAST:event_vertotalActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
     produto pf = new produto();
        if(local.getText().equals("") && entregar.isSelected()||pedido.getText().equals("")||quantp.getSelectedItem().equals("0")||pizza.getSelectedItem().equals("Selecione")
        ||refri.getSelectedItem().equals("Selecione")&& !srefri.isSelected()){
           JOptionPane.showMessageDialog(null,"Preencha as lacunas");
       }
        else if(!buscar.isSelected()&&!entregar.isSelected()){
            JOptionPane.showMessageDialog(null,"Marque algo");
        }
        else if(pedir.isEnabled()){
            JOptionPane.showMessageDialog(null,"Você so pode atualizar se tiver pedido antes");
            }
        else{
    
      pf.setPedido((Integer.parseInt(pedido.getText())));
      pf.setLocal(local.getText());
      pf.setPizza((String)pizza.getSelectedItem());
       pf.setRefri((String)refri.getSelectedItem());
       pf.setQuantp((Integer.parseInt((String)quantp.getSelectedItem())));
        pf.setQuantr(Integer.parseInt((String)quantr.getSelectedItem()));
        pf.setSrefri((Boolean)srefri.isSelected());
        pf.setSazeitona((Boolean)sazeitona.isSelected());
        pf.setKetchup((Boolean)ketchup.isSelected());
        pf.setBuscar((Boolean)buscar.isSelected());
        pf.setEntregar((Boolean)entregar.isSelected());
        
      
      
        JOptionPane.showMessageDialog(null, pf.AtualizarCC());
       
    
     finalizar.setEnabled(true);
     pedir.setEnabled(true);
        }
    }//GEN-LAST:event_atualizarActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
          if(local.isEnabled()||pizza.isEnabled()||refri.isEnabled() && !srefri.isSelected()||quantp.isEnabled()||quantr.isEnabled()
                  ||sazeitona.isEnabled()||srefri.isEnabled()||pizzad.isEnabled()||buscar.isEnabled()
                  ||pedido.isEnabled()||entregar.isEnabled()||ketchup.isEnabled()){
            JOptionPane.showMessageDialog(null,"Pesquise algo primeiro");
        pedir.setEnabled(true);
        }
        else{
        if(srefri.isSelected())
        {
          local.setEnabled(true);
      quantr.setEnabled(false);
      quantp.setEnabled(true);
       refri.setEnabled(false);
     pizza.setEnabled(true);
     sazeitona.setEnabled(true); 
     srefri.setEnabled(true);
     pizzad.setEnabled(true); 
     buscar.setEnabled(true);
     pedir.setEnabled(false);
     entregar.setEnabled(true);
     ketchup.setEnabled(true);
     pedido.setEnabled(true);
        }
        else
        {
              local.setEnabled(true);
      quantr.setEnabled(true);
      quantp.setEnabled(true);
       refri.setEnabled(true);
     pizza.setEnabled(true);
     sazeitona.setEnabled(true); 
     srefri.setEnabled(true);
     pizzad.setEnabled(true); 
     buscar.setEnabled(true);
     pedir.setEnabled(false);
     entregar.setEnabled(true);
     ketchup.setEnabled(true);
     pedido.setEnabled(true);
        }
     
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void cardapioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardapioActionPerformed
       
        
        if(evt.getSource() == cardapio){
        
           JOptionPane.showMessageDialog(null,"CARDAPIO"+"\n"+"\nCalabresa = R$ 25,00"+
"\nMussalera = R$ 23,00"+
"\nPortuguesa = R$ 24,00"+
"\nFrango com Catupiry = R$ 26,00"+
"\nEspecial - Pizzarela = R$ 30,00"+
"\n"+
"\nChocolate = R$ 26,00"+
"\nBeijinho = R$ 27,00"+
"\nChocolate Branco = R$ 22,00"+
"\nBrigadeiro = R$ 25,00"+
"\n"+
"\nRefris (2L) -"+

"\nCoca - Cola = R$ 6,00"+

"\nPepsi = R$ 4,50"+

"\nFanta(Geral) = R$ 4,60"+

"\nGuarana-Jesus = R$ 3,50"+

"\nKuat = R$ 5,00"+

"\nSukita = R$ 3,00");
       }
       
    }//GEN-LAST:event_cardapioActionPerformed

    private void contatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contatoActionPerformed
        try{
            JOptionPane.showMessageDialog(null,"Contato: 98558-5542."+"\n Nós ligue para tirar duvidas");
        }
        catch(Exception error){

        }

    }//GEN-LAST:event_contatoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(comprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new comprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JButton atualizar;
    private javax.swing.JRadioButton buscar;
    private javax.swing.JButton cancelar;
    private javax.swing.JToggleButton cardapio;
    private javax.swing.JButton contato;
    private javax.swing.JRadioButton entregar;
    private javax.swing.JButton finalizar;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JCheckBox ketchup;
    private javax.swing.JTextField local;
    private javax.swing.JFormattedTextField pedido;
    private javax.swing.JButton pedir;
    private javax.swing.JComboBox<String> pizza;
    private javax.swing.JCheckBox pizzad;
    private javax.swing.JComboBox<String> quantp;
    private javax.swing.JComboBox<String> quantr;
    private javax.swing.JComboBox<String> refri;
    private javax.swing.JCheckBox sazeitona;
    private javax.swing.JCheckBox srefri;
    private javax.swing.JLabel telacad;
    private javax.swing.JFormattedTextField total;
    private javax.swing.JLabel usuario1;
    private javax.swing.JLabel usuario2;
    private javax.swing.JLabel usuario3;
    private javax.swing.JLabel usuario4;
    private javax.swing.JLabel usuario5;
    private javax.swing.JButton verpedido;
    private javax.swing.JButton vertotal;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables
}
