/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pizza.view;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import pizza.model.clientes;
import pizza.model.produto_fornecer;

/**
 *
 * @author aluno
 */
public class principal_f extends javax.swing.JFrame {

    /**
     * Creates new form principal_f
     */
    public principal_f() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jSpinner1 = new javax.swing.JSpinner();
        Voltar = new javax.swing.JButton();
        txtcodigo = new javax.swing.JLabel();
        codigo = new javax.swing.JTextField();
        nome2 = new javax.swing.JLabel();
        outros = new javax.swing.JCheckBox();
        massa = new javax.swing.JCheckBox();
        alimentos = new javax.swing.JCheckBox();
        temperos = new javax.swing.JCheckBox();
        nome3 = new javax.swing.JLabel();
        marcas = new javax.swing.JTextField();
        refrigerantes = new javax.swing.JCheckBox();
        pedir = new javax.swing.JButton();
        contato = new javax.swing.JButton();
        verpedido = new javax.swing.JButton();
        local = new javax.swing.JComboBox<>();
        nome4 = new javax.swing.JLabel();
        nome5 = new javax.swing.JLabel();
        uf = new javax.swing.JComboBox<>();
        nome6 = new javax.swing.JLabel();
        quant = new javax.swing.JTextField();
        atualizar = new javax.swing.JButton();
        alterar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        finalizar = new javax.swing.JButton();
        telacad = new javax.swing.JLabel();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        Voltar.setBackground(new java.awt.Color(207, 84, 25));
        Voltar.setText("<");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(0, 0, 40, 23);

        txtcodigo.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        txtcodigo.setForeground(new java.awt.Color(1, 1, 1));
        txtcodigo.setText("Codigo:");
        getContentPane().add(txtcodigo);
        txtcodigo.setBounds(10, 330, 150, 30);

        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });
        getContentPane().add(codigo);
        codigo.setBounds(90, 330, 120, 30);

        nome2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        nome2.setForeground(new java.awt.Color(1, 1, 1));
        nome2.setText("Fornecer:");
        getContentPane().add(nome2);
        nome2.setBounds(20, 140, 110, 30);

        outros.setText("Outros");
        outros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outrosActionPerformed(evt);
            }
        });
        getContentPane().add(outros);
        outros.setBounds(310, 170, 110, 40);

        massa.setText("Massa");
        getContentPane().add(massa);
        massa.setBounds(200, 200, 55, 40);

        alimentos.setText("Alimentos");
        alimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentosActionPerformed(evt);
            }
        });
        getContentPane().add(alimentos);
        alimentos.setBounds(70, 170, 71, 40);

        temperos.setText("Temperos/Molho");
        getContentPane().add(temperos);
        temperos.setBounds(70, 200, 140, 40);

        nome3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        nome3.setForeground(new java.awt.Color(1, 1, 1));
        nome3.setText("Entregar em:");
        getContentPane().add(nome3);
        nome3.setBounds(220, 290, 130, 30);

        marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcasActionPerformed(evt);
            }
        });
        getContentPane().add(marcas);
        marcas.setBounds(90, 250, 120, 30);

        refrigerantes.setText("Refrigerantes");
        refrigerantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refrigerantesActionPerformed(evt);
            }
        });
        getContentPane().add(refrigerantes);
        refrigerantes.setBounds(200, 170, 110, 40);

        pedir.setBackground(new java.awt.Color(255, 102, 0));
        pedir.setText("PEDIR");
        pedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pedirActionPerformed(evt);
            }
        });
        getContentPane().add(pedir);
        pedir.setBounds(380, 460, 100, 23);

        contato.setBackground(new java.awt.Color(255, 102, 0));
        contato.setText("CONTATO");
        contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contatoActionPerformed(evt);
            }
        });
        getContentPane().add(contato);
        contato.setBounds(10, 460, 90, 23);

        verpedido.setBackground(new java.awt.Color(255, 102, 0));
        verpedido.setText("VER PEDIDO");
        verpedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verpedidoActionPerformed(evt);
            }
        });
        getContentPane().add(verpedido);
        verpedido.setBounds(110, 460, 120, 23);

        local.setBackground(new java.awt.Color(255, 132, 0));
        local.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Rua Argentina,Bairro Cocaina", "Rua dos Mares,Bairro Morto Mota", "Rua dos Corns,Bairro Mara", "Rua dos Expertinhos,Bairro Malakoi" }));
        local.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localActionPerformed(evt);
            }
        });
        getContentPane().add(local);
        local.setBounds(310, 290, 140, 30);

        nome4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        nome4.setForeground(new java.awt.Color(1, 1, 1));
        nome4.setText("Marcas:");
        getContentPane().add(nome4);
        nome4.setBounds(10, 250, 80, 30);

        nome5.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        nome5.setForeground(new java.awt.Color(1, 1, 1));
        nome5.setText("UF:");
        getContentPane().add(nome5);
        nome5.setBounds(250, 250, 80, 30);

        uf.setBackground(new java.awt.Color(255, 132, 0));
        uf.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "SP", "CE", "PE", "PA", "RS", "RJ" }));
        uf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ufActionPerformed(evt);
            }
        });
        getContentPane().add(uf);
        uf.setBounds(290, 250, 100, 30);

        nome6.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 18)); // NOI18N
        nome6.setForeground(new java.awt.Color(1, 1, 1));
        nome6.setText("Quant:");
        getContentPane().add(nome6);
        nome6.setBounds(10, 290, 150, 30);

        quant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quantActionPerformed(evt);
            }
        });
        getContentPane().add(quant);
        quant.setBounds(90, 290, 120, 30);

        atualizar.setBackground(new java.awt.Color(255, 102, 0));
        atualizar.setText("ATUALIZAR ");
        atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atualizarActionPerformed(evt);
            }
        });
        getContentPane().add(atualizar);
        atualizar.setBounds(250, 460, 120, 23);

        alterar.setBackground(new java.awt.Color(255, 102, 0));
        alterar.setText("Alt");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });
        getContentPane().add(alterar);
        alterar.setBounds(420, 0, 60, 23);

        cancelar.setBackground(new java.awt.Color(255, 102, 0));
        cancelar.setText("CANCELAR");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(380, 420, 100, 23);

        finalizar.setBackground(new java.awt.Color(255, 102, 0));
        finalizar.setText("FINALIZAR");
        finalizar.setEnabled(false);
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(finalizar);
        finalizar.setBounds(250, 420, 120, 23);

        telacad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cadastro.png"))); // NOI18N
        getContentPane().add(telacad);
        telacad.setBounds(0, 0, 500, 500);

        setBounds(0, 0, 500, 540);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        fornecer f = new fornecer();
        f.setVisible(true);
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigoActionPerformed

    private void alimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alimentosActionPerformed

    private void outrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outrosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_outrosActionPerformed

    private void marcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcasActionPerformed

    private void refrigerantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refrigerantesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_refrigerantesActionPerformed

    private void contatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contatoActionPerformed
        try{
         JOptionPane.showMessageDialog(null,"Contato: 85-99767-5676."+"\n Nós ligue para tirar duvidas");   
        }
        catch(Exception error){
        
        }
        
    }//GEN-LAST:event_contatoActionPerformed

    private void localActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localActionPerformed

    private void ufActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ufActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ufActionPerformed

    private void pedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pedirActionPerformed
       produto_fornecer pf = new produto_fornecer();
        if(local.getSelectedItem().equals("Selecione")||uf.getSelectedItem().equals("Selecione")||quant.getText().equals("")||
          codigo.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Preencha as lacunas");
       }
        else if(!alimentos.isSelected()&& !massa.isSelected()&& !temperos.isSelected()
                && !outros.isSelected()&& !refrigerantes.isSelected()){
            JOptionPane.showMessageDialog(null,"Marque algo");
        }
        else{
      pf.setLocal((String)local.getSelectedItem());
      pf.setUf((String)uf.getSelectedItem());
      pf.setRefrigerantes((Boolean)refrigerantes.isSelected());
      pf.setAlimentos((Boolean)alimentos.isSelected());
      pf.setMassa((Boolean)massa.isSelected());
      pf.setTempero((Boolean)temperos.isSelected());
      pf.setOutros((Boolean)outros.isSelected());
      pf.setMarcas(marcas.getText());
      pf.setQuant((Integer.parseInt(quant.getText())));
      pf.setCod((Integer.parseInt(codigo.getText())));
      
        JOptionPane.showMessageDialog(null, pf.SalvarF());
       
      local.setSelectedItem(0);
      uf.setSelectedItem(0);
      refrigerantes.setSelected(false);
      marcas.setText("");
     temperos.setSelected(false);
     massa.setSelected(false); 
     alimentos.setSelected(false);
     outros.setSelected(false); 
     codigo.setText("");
     quant.setText("");
     finalizar.setEnabled(true);
        }
    
     
      
    }//GEN-LAST:event_pedirActionPerformed

    private void quantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quantActionPerformed

    private void atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atualizarActionPerformed
        produto_fornecer pf = new produto_fornecer();
        if(local.getSelectedItem().equals("")||uf.getSelectedItem().equals("")||quant.getText().equals("")||
          codigo.getText().equals("")){
           JOptionPane.showMessageDialog(null,"Preencha as lacunas");
       }
        else if(!alimentos.isSelected()&& !massa.isSelected()&& !temperos.isSelected()
                && !outros.isSelected()&& !refrigerantes.isSelected()){
            JOptionPane.showMessageDialog(null,"Marque algo");
        }
        else if (pedir.isEnabled()){
            JOptionPane.showMessageDialog(null,"Peça primeiro para poder atualizar");
        }
        else{
      pf.setLocal((String)local.getSelectedItem());
      pf.setUf((String)uf.getSelectedItem());
      pf.setRefrigerantes((Boolean)refrigerantes.isSelected());
      pf.setAlimentos((Boolean)alimentos.isSelected());
      pf.setMassa((Boolean)massa.isSelected());
      pf.setTempero((Boolean)temperos.isSelected());
      pf.setOutros((Boolean)outros.isSelected());
      pf.setMarcas(marcas.getText());
      pf.setQuant((Integer.parseInt(quant.getText())));
      pf.setCod((Integer.parseInt(codigo.getText())));
      
        JOptionPane.showMessageDialog(null, pf.AtualizarF());
       
      local.setSelectedItem(0);
      uf.setSelectedItem(0);
      refrigerantes.setSelected(false);
      marcas.setText("");
     temperos.setSelected(false);
     massa.setSelected(false); 
     alimentos.setSelected(false);
     outros.setSelected(false); 
     codigo.setText("");
     pedir.setEnabled(true);
     quant.setText("");
     finalizar.setEnabled(true);
        }
    
    }//GEN-LAST:event_atualizarActionPerformed

    private void verpedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verpedidoActionPerformed
          if(evt.getSource()== verpedido){
            try {
                String ccode = JOptionPane.showInputDialog("Digite o código: ");
                BufferedReader bf = new BufferedReader(new FileReader(ccode+"ff.txt"));
                // criando o arquivo de leitura de caracteres
                
                codigo.setText(bf.readLine());
                local.setSelectedItem(bf.readLine());
                marcas.setText(bf.readLine());
                uf.setSelectedItem(bf.readLine());
                quant.setText(bf.readLine());
               alimentos.setSelected(Boolean.parseBoolean(bf.readLine()));
               massa.setSelected(Boolean.parseBoolean(bf.readLine()));
               temperos.setSelected(Boolean.parseBoolean(bf.readLine()));
               refrigerantes.setSelected(Boolean.parseBoolean(bf.readLine()));
                outros.setSelected(Boolean.parseBoolean(bf.readLine()));
                bf.close();
           local.setEnabled(false);
      uf.setEnabled(false);
      refrigerantes.setEnabled(false);
      marcas.setEnabled(false);
     temperos.setEnabled(false);
     massa.setEnabled(false); 
     alimentos.setEnabled(false);
     outros.setEnabled(false); 
     codigo.setEnabled(false);
     pedir.setEnabled(false);
     quant.setEnabled(false);
                
                
            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro: " +erro.getMessage());
                Logger.getLogger(cadastro.class.getName()).log(Level.SEVERE, null, erro);
         local.setEnabled(true);
         marcas.setEnabled(true);
         uf.setEnabled(true);
          refrigerantes.setEnabled(true);
          massa.setEnabled(true);
          temperos.setEnabled(true);
          alimentos.setEnabled(true);
          outros.setEnabled(true);
          codigo.setEnabled(true);
          pedir.setEnabled(true);
          quant.setEnabled(true);
            }
        
        }        // TODO add your handling code here:
    }//GEN-LAST:event_verpedidoActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed

        
        // TODO add your handling code here:
        if(local.isEnabled()||marcas.isEnabled()||uf.isEnabled()||refrigerantes.isEnabled()||
          massa.isEnabled()||temperos.isEnabled()|| alimentos.isEnabled()||
          outros.isEnabled()|codigo.isEnabled()||pedir.isEnabled()||quant.isEnabled()){
            JOptionPane.showMessageDialog(null,"Pesquise algo primeiro");
        pedir.setEnabled(true);
        }
        else{
        local.setEnabled(true);
         marcas.setEnabled(true);
         uf.setEnabled(true);
          refrigerantes.setEnabled(true);
          massa.setEnabled(true);
          temperos.setEnabled(true);
          alimentos.setEnabled(true);
          outros.setEnabled(true);
          codigo.setEnabled(true);
          pedir.setEnabled(false);
          quant.setEnabled(true);
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
try{
        int cod = Integer.parseInt(JOptionPane.showInputDialog("Digite o código "));
        produto_fornecer Clientes = new produto_fornecer();
        Clientes.setCod(cod);
        JOptionPane.showMessageDialog(null, Clientes.Deletar());    
        local.setEnabled(true);
         marcas.setEnabled(true);
         uf.setEnabled(true);
          refrigerantes.setEnabled(true);
          massa.setEnabled(true);
          temperos.setEnabled(true);
          alimentos.setEnabled(true);
          outros.setEnabled(true);
          codigo.setEnabled(true);
          quant.setEnabled(true);
     local.setSelectedItem(0);
      uf.setSelectedItem(0);
      refrigerantes.setSelected(false);
      marcas.setText("");
     temperos.setSelected(false);
     massa.setSelected(false); 
     alimentos.setSelected(false);
     outros.setSelected(false); 
     codigo.setText("");
   
     quant.setText("");
        
   }
    catch (Exception erro) {
                JOptionPane.showMessageDialog(null, "Erro: " +erro.getMessage());
                Logger.getLogger(cadastro.class.getName()).log(Level.SEVERE, null, erro);
   
    }        // TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        JOptionPane.showMessageDialog(null,"Obrigado por fornecer serviços para a Pizzarela!");
        System.exit(0);
    }//GEN-LAST:event_finalizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal_f.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal_f().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JCheckBox alimentos;
    private javax.swing.JButton alterar;
    private javax.swing.JButton atualizar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField codigo;
    private javax.swing.JButton contato;
    private javax.swing.JButton finalizar;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JComboBox<String> local;
    private javax.swing.JTextField marcas;
    private javax.swing.JCheckBox massa;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel nome3;
    private javax.swing.JLabel nome4;
    private javax.swing.JLabel nome5;
    private javax.swing.JLabel nome6;
    private javax.swing.JCheckBox outros;
    private javax.swing.JButton pedir;
    private javax.swing.JTextField quant;
    private javax.swing.JCheckBox refrigerantes;
    private javax.swing.JLabel telacad;
    private javax.swing.JCheckBox temperos;
    private javax.swing.JLabel txtcodigo;
    private javax.swing.JComboBox<String> uf;
    private javax.swing.JButton verpedido;
    // End of variables declaration//GEN-END:variables
}
